# Generated by Django 5.2.6 on 2025-11-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='артикул')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'спецификация',
                'verbose_name_plural': 'спецификация',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='артикул')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='единица измерения')),
                ('name_full', models.CharField(max_length=20, verbose_name='полное название')),
            ],
            options={
                'verbose_name': 'единица измерения',
                'verbose_name_plural': 'единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='код')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='код')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'работы',
            },
        ),
        migrations.CreateModel(
            name='BOMtoBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='количество')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parentok', to='articles.bom', verbose_name='изделие')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='childok', to='articles.bom', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'связь изделие-изделие',
                'verbose_name_plural': 'связи изделие-изделие',
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='boms',
            field=models.ManyToManyField(through='articles.BOMtoBOM', to='articles.bom'),
        ),
        migrations.CreateModel(
            name='MaterialBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='количество')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.bom', verbose_name='изделие')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.material', verbose_name='материал')),
            ],
            options={
                'verbose_name': 'связь материал-изделие',
                'verbose_name_plural': 'связи материал-изделие',
            },
        ),
        migrations.CreateModel(
            name='MaterialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.material', verbose_name='материал')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.unit', verbose_name='единица измерения')),
            ],
            options={
                'verbose_name': 'связь материал-единица измерения',
                'verbose_name_plural': 'связи материал-единица измерения',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.unit', verbose_name='единица измерения'),
        ),
        migrations.AddField(
            model_name='bom',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.unit', verbose_name='единица измерения'),
        ),
        migrations.CreateModel(
            name='WarehouseBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='количество')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.bom', verbose_name='изделие')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'связь склад-изделие',
                'verbose_name_plural': 'связи склад-изделие',
            },
        ),
        migrations.CreateModel(
            name='WorkBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='количество')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.bom', verbose_name='изделие')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.work', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'связь работа-изделие',
                'verbose_name_plural': 'связи работа-изделие',
            },
        ),
        migrations.CreateModel(
            name='WarehouseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.material', verbose_name='материал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'связь склад-материал',
                'verbose_name_plural': 'связи склад-материал',
                'unique_together': {('warehouse', 'material')},
            },
        ),
    ]
