# Generated by Django 5.2.6 on 2025-09-23 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='артикул')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('unit', models.CharField(max_length=3, verbose_name='единица измерения')),
            ],
            options={
                'verbose_name': 'спецификация',
                'verbose_name_plural': 'спецификация',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='артикул')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('unit', models.CharField(max_length=3, verbose_name='единица измерения')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='артикул')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('unit', models.CharField(max_length=3, verbose_name='единица измерения')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'изделие',
                'verbose_name_plural': 'изделия',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='код')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='код')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'работы',
            },
        ),
        migrations.CreateModel(
            name='MaterialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.material', verbose_name='материал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.product', verbose_name='изделие')),
            ],
            options={
                'verbose_name': 'связь материал-изделие',
                'verbose_name_plural': 'связи материал-изделие',
            },
        ),
        migrations.CreateModel(
            name='WarehouseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.material', verbose_name='материал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'связь склад-материал',
                'verbose_name_plural': 'связи склад-материал',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.product', verbose_name='изделие')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'связь склад-изделие',
                'verbose_name_plural': 'связи склад-изделие',
            },
        ),
    ]
