# Generated by Django 5.2.6 on 2025-11-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contractors.contractor', verbose_name='поставщик'),
            preserve_default=False,
        ),
    ]
