# Generated by Django 5.2.6 on 2025-11-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'контрагент',
                'verbose_name_plural': 'контрагент',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='код')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В производстве'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractor', verbose_name='контрагент')),
                ('target_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.warehouse', verbose_name='склад готовой продукции')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='код')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.contractor', verbose_name='клиент')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'отгрузка',
                'verbose_name_plural': 'отгрузка',
            },
        ),
        migrations.CreateModel(
            name='ShippingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.material', verbose_name='материалы')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.shipping', verbose_name='отгрузка')),
            ],
            options={
                'verbose_name': 'связь отгрузка-материал',
                'verbose_name_plural': 'связи отгрузка-материал',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='код')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.contractor', verbose_name='поставщик')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'поставки',
            },
        ),
        migrations.CreateModel(
            name='SupplyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.material', verbose_name='материалы')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.supply', verbose_name='поставка')),
            ],
            options={
                'verbose_name': 'связь поставка-материал',
                'verbose_name_plural': 'связи поставка-материал',
            },
        ),
    ]
